WashWise.Web/Controllers/AdminReportsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WashWise.Services.Contracts;
using static WashWise.Web.Common.CommonConstants;

namespace WashWise.Web.Controllers
{
    [Authorize(Roles = AdministratorRoleName)]
    public class AdminReportsController : Controller
    {
        private readonly IReportService _reportService;

        public AdminReportsController(IReportService reportService)
        {
            _reportService = reportService;
        }

        public async Task<IActionResult> Index()
        {
            var reports = await _reportService.GetAllAsync();
            return View(reports);
        }

        public async Task<IActionResult> Details(Guid reportId)
        {
            var report = await _reportService.GetByIdAsync(reportId);

            if (report == null) return NotFound();

            return View(report);
        }

        public async Task<IActionResult> ResolveReport(Guid reportId)
        {
            var isResolved = await _reportService.MarkAsResolved(reportId);

            if (!isResolved)
            {
                TempData["Error"] = "Нещо се обърка, моля опитайте пак!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

WashWise.Web/Views/AdminReports/Details.cshtml
@using WashWise.Models

@model Report

<p class="m-0 mt-3 text-body-emphasis text-3xl tracking-tight leading-10 fw-bold mb-2 d-flex">
    Детайли за повреда
    @if (!Model.IsResolved)
    {
        <a class=" btn btn-lg btn-success text-white text-sm fw-semibold" asp-controller="AdminReports" asp-action="ResolveReport" asp-route-reportId="@Model.Id" style="color: #fff; margin-left: 10px;">Маркирай като решена</a>
    }
</p>
<p><strong>Машина:</strong> @Model.WashingMachine.Model</p>
<p><strong>Описание:</strong> @Model.Description</p>
<p><strong>Статус:</strong> @(Model.IsResolved ? "Решена" : "Нерешена")</p>
<p><strong>Автор:</strong> @Model.Author?.Email</p>
<p><strong>Докладвано на:</strong> @Model.GeneratedAt.ToString("dd.MM.yyyy")</p>

<a class="btn btn-secondary" asp-controller="AdminReports" asp-action="Index" style="color: #fff;">Назад</a>

WashWise.Web/Views/AdminReports/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using WashWise.Models
@model IEnumerable<Report>

<p class="m-0 mt-3 text-body-emphasis text-3xl tracking-tight leading-10 fw-bold mb-2 d-flex justify-content-between">
    Докладвани повреди
    <div class="form-group" style="margin-left: 10px;">
        <label for="isResolvedFilter" class="form-label">Статус:</label>
        <select id="isResolvedFilter" class="form-select w-auto d-inline-block">
            <option value="all">Всички</option>
            <option value="resolved">Решени</option>
            <option value="unresolved">Нерешени</option>
        </select>
    </div>

</p>

@if (Model.Any())
{
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Машина</th>
            <th>Описание</th>
            <th>Статус</th>
            <th>Автор</th>
            <th>Докладвано на</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var report in Model)
        {
            <tr data-is-resolved="@(report.IsResolved ? "true" : "false")">
                <td>@report.WashingMachine.Model</td>
                <td>@(report.Description.Length > 40 ? (report.Description[..40] + "...") : report.Description)</td>
                <td>@(report.IsResolved ? "Решена" : "Нерешена")</td>
                <td>@(report.Author?.Email)</td>
                <td>@report.GeneratedAt.ToString("dd.MM.yyyy HH:mm")</td>
                <td>
                    <a class="btn btn-info btn-sm" asp-controller="AdminReports" asp-action="Details" asp-route-reportId="@report.Id" style="color: #fff">Виж детайли</a>

                    @if (!report.IsResolved)
                    {
                        <a asp-controller="AdminReports" asp-action="ResolveReport" asp-route-reportId="@report.Id" class="btn btn-success btn-sm text-white">Маркирай като решена
                        </a>
                    }
                </td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <p>Няма повреди, отговарящи на зададения критерий.</p>
}